In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [2]:
car=pd.read_csv('quikr_car.csv')

In [3]:
car

name    company  year          Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000   
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000   
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price   
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000   
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000   
..                                      ...        ...   ...            ...   
887                                      Ta       Tara  zest       3,10,000   
888                     Tata Zest XM Diesel       Tata  2018       2,60,000   
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000   
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000   
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000   

     kms_driven fuel_type  
0    45,000 kms    Petrol  
1        40 kms    Diesel  
2    22,000 kms    Petrol  
3    28,000 kms    Petrol  
4    36,000 kms    Diesel  
..          ...       ...  
887         NaN       NaN  
888  27,000 kms    Diesel  
889  40,000 kms    Diesel  
890      Petrol       NaN  
891      Petrol       NaN  

[892 rows x 6 columns]

In [5]:
# now we have to predict the price using all the independent columns 
car.shape

(892, 6)

In [8]:
car.info()
# info of the dataframe 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


In [10]:
car["year"].unique()
# this helps is to find the the unique values of the column 

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [11]:
car["Price"].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [12]:
# making the backup of the data 
backup=car.copy()

# cleaning of the data 

In [18]:
car=car[car["year"].str.isnumeric()]

In [20]:
car.shape


(842, 6)

In [24]:
car["year"]=car["year"].astype(int)
# changing the datatype of the year column 

C:\Users\pranj\AppData\Local\Temp\ipykernel_17112\2306994036.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car["year"]=car["year"].astype(int)


In [25]:
car["year"].dtype

dtype('int32')

In [26]:
car["Price"]

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...      
886         3,00,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 842, dtype: object

In [27]:
# in price we need only the numeric values
car=car[car["Price"]!="Ask For Price"]

In [28]:
car["Price"].dtype

dtype('O')

In [32]:
# remove the coomas with the empty string 
car["Price"]=car["Price"].str.replace(",","").astype(int)

In [35]:
# now we also have to convert the price of the car into the integer datatype 
car["Price"].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169

In [36]:
car["kms_driven"]

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...     
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [39]:
# split the string and then remove the comma and then convert it into the int datatype 
car["kms_driven"]=car["kms_driven"].str.split(" ").str.get(0).str.replace(",","")

In [41]:
car=car[car["kms_driven"].str.isnumeric()]

In [45]:
# chaning the datatype of the string into the int datatype 
car["kms_driven"]=car["kms_driven"].astype(int)

In [46]:
car["kms_driven"].dtype

dtype('int32')

In [49]:
car=car[~car["fuel_type"].isna()]
# so it is having the fuel nan value 

# so ~ excluding this row we are keeping all the rows

In [50]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32 
 3   Price       816 non-null    int32 
 4   kms_driven  816 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB


In [51]:
car["name"]

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...                  
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [54]:
car["name"]=car["name"].str.split(" ").str.slice(0,3).str.join(" ")

In [55]:
car["name"]

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
3           Hyundai Grand i10
4      Ford EcoSport Titanium
6                   Ford Figo
                ...          
883        Maruti Suzuki Ritz
885            Tata Indica V2
886      Toyota Corolla Altis
888              Tata Zest XM
889        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [58]:
# reseting the index
car=car.reset_index(drop=True)

In [61]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32 
 3   Price       816 non-null    int32 
 4   kms_driven  816 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB


In [62]:
# cleaned data
car.head()

name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [70]:
# checking for the outliers
car=car[car["Price"]<6000000].reset_index(drop=True)

# so removing the outliers 

In [71]:
car.to_csv('Cleaned_Car_data.csv')

# Building the modal 

In [75]:
X=car.drop(["Price"],axis="columns")
X

name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [76]:
y=car["Price"]
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [77]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [78]:
X_test

name    company  year  kms_driven fuel_type
396    Hyundai Grand i10    Hyundai  2016       59910    Diesel
105   Maruti Suzuki Alto     Maruti  2012       14000    Petrol
445    Toyota Corolla H2     Toyota  2003      100000    Petrol
515   Maruti Suzuki Alto     Maruti  2010       55000    Petrol
514  Maruti Suzuki Wagon     Maruti  2009       35000    Petrol
..                   ...        ...   ...         ...       ...
181     Skoda Fabia 1.2L      Skoda  2011       38200    Diesel
182        Mini Cooper S       Mini  2013       13000    Petrol
617    Maruti Suzuki Zen     Maruti  2008       46000    Petrol
120      Chevrolet Spark  Chevrolet  2012       33600    Petrol
347      Mahindra XUV500   Mahindra  2015       15000    Diesel

[163 rows x 5 columns]

In [83]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

# r2score is used to measure the score of the regression 

In [80]:
# now we will convert the categorical data into the one hot encoding into the 
# numeric data 
ohe=OneHotEncoder()
# making the object 
ohe.fit(X[["name","company","fuel_type"]])

OneHotEncoder()

In [91]:
# now transform the columns 
from sklearn.compose import make_column_transformer
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),["name","company","fuel_type"]),remainder="passthrough")

# it will transform the columns

In [92]:
lr=LinearRegression()

In [93]:
pipe=make_pipeline(column_trans,lr)
# so pipeline will make the flow of the program to be follow 

# first it will go into the column transform and then it will dump into the modal 

In [94]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [106]:
y_predicated=pipe.predict(X_test)
y_predicated.round()

array([ 423848.,  178518.,  270747.,  109649.,  137708.,  524762.,
        602282.,  244273.,  522427.,  476746.,  403799.,  179058.,
        349633.,  281924.,  320227.,  283752.,  581634.,   38542.,
        714792.,  -38434.,  735593.,  100454.,  197949.,  142715.,
         75428.,  536324.,  663656.,  154460.,  155027.,  350146.,
        342972.,  130809.,   71789.,  184825.,  320097.,  534346.,
       1585058.,  517755.,  433392.,  212489.,  177560.,  303818.,
        305415.,  379033.,  405856.,  279638.,  158260.,  348992.,
        216362.,  373043.,  511964.,  416599., 1056049.,  246981.,
        636381.,  270878.,   90201., 1505041., 2173871., 1534442.,
        433244.,  435352.,  581815.,  536785.,  282902.,  300840.,
        268786.,   16340.,  207510.,  464289.,  331551.,  109405.,
        303270.,  193693.,  351872.,  315479.,   74874.,   52301.,
        606309.,  370309.,  348130.,  264734.,  298624.,  250588.,
        393835.,  305743.,  190314.,  557443.,  187385.,  2489

In [107]:
y_predicated

array([ 423847.68072335,  178518.18406767,  270746.7464166 ,
        109649.18084066,  137707.74111623,  524762.13544308,
        602282.24187265,  244272.86190085,  522427.30756126,
        476746.10688177,  403798.8740584 ,  179058.37737712,
        349632.67016343,  281923.74727761,  320227.02862431,
        283751.70683931,  581633.9861357 ,   38542.13803759,
        714792.48061168,  -38433.94448296,  735593.49243781,
        100453.8843483 ,  197948.74865781,  142715.37194362,
         75428.16703855,  536324.3540038 ,  663656.38298278,
        154459.67632799,  155027.16083618,  350145.51079424,
        342971.77966018,  130809.4425771 ,   71788.77868198,
        184825.09570991,  320097.15286205,  534346.3116245 ,
       1585057.78449072,  517755.18965527,  433391.53669924,
        212488.82774723,  177560.18398255,  303818.39208287,
        305414.78640223,  379033.32416118,  405856.47307134,
        279637.96938255,  158259.79683163,  348992.27462056,
        216361.53731298,

In [109]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predicated)

0.7801835943535889

In [116]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_predicated=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_predicated))

In [117]:
np.argmax(scores)

433

In [115]:
scores[np.argmax(scores)]

0.8341189574324746

In [118]:
# now dump the pipeline 
import pickle 
with open("LinearRegressionModel","wb") as f:
    pickle.dump(pipe,f)

In [119]:
pipe.predict(pd.DataFrame([["Maruti Suzuki Swift","Maruti",2019,100,"Petrol"]],columns=["name","company","year","kms_driven","fuel_type"]))

array([431213.54164956])